[package]
name = "tree_diameter"
version = "0.1.0"
edition = "2024"

[dependencies]
graph = { version = "0.1.0", path = "../../../../crates/graph/graph" }
proconio = { version = "0.5.0", features = ["derive"] }
