[package]
name = "verify"
version = "0.1.0"
edition = "2024"

[dependencies]
proconio = { version = "0.5.0", features = ["derive"] }
ds = { path = "../ds" }

[[bin]]
name = "dsu"
path = "src/ds/dsu.rs"