[package]
name = "unionfind"
version = "0.1.0"
edition = "2021"

[dependencies]
dsu = { version = "0.1.0", path = "../../../../crates/ds/dsu" }
proconio = { version = "0.5.0", features = ["derive"] }
